const data = {
    product:[
        {
            _id:'1',
            name:'Nike Slim Shirt',
            category:'Shirts',
            image:'/images/d1.jpg',
            price: 120,
            brand:'Nike',
            rating:4.5,
            numReviews: 10,
            description : 'high quality product',
        },
        {
            _id:'2',
            name:'Nike  Shirt',
            category:'Shirts',
            image:'/images/d1.jpg',
            price: 220,
            brand:'Nike',
            rating:3.5,
            numReviews: 12,
            description : 'high quality product',
        },
        {
            _id:'3',
            name:' Slim Shirt',
            category:'Shirts',
            image:'/images/d1.jpg',
            price: 300,
            brand:'Nike',
            rating:4,
            numReviews: 7,
            description : 'high quality product',
        },
        {
            _id:'4',
            name:'Nike Slim Shirt',
            category:'Shirts',
            image:'/images/d1.jpg',
            price: 170,
            brand:'Nike',
            rating:4.5,
            numReviews: 14,
            description : 'high quality product',
        },
        {
            _id:'6',
            name:'Nike Abdell Shirt',
            category:'Shirts',
            image:'/images/d1.jpg',
            price: 220,
            brand:'Nike',
            rating:3.5,
            numReviews: 12,
            description : 'high quality product',
        },
    ],
};
export default data;